import { Injectable } from '@angular/core';
import { catchError, combineLatest, map, Observable, of, startWith, Subject, switchMap, tap } from 'rxjs';
import { BaseResponse } from 'src/app/shared/models/base-response.model';
import { environment } from 'src/environments/environment';
import { HttpClient, HttpParams } from '@angular/common/http';
import { AddAppointmentRequestData, Appointment, UpdateDurationRequestData } from '../../shared/models/appointment.model';
import { AppointmentStatus, ReadStatus, Status } from '../../shared/models/status';
import { RoomType } from '../../shared/models/rooms.model';
import { AvailabilityType, User, UserType } from '../../shared/models/user.model';
import { Weekday } from '../../shared/models/calendar.model';
import { PhysicianApiService } from './physician.api.service';
import { StaffApiService } from './staff-api.service';
import { Physician } from '../../shared/models/physician.model';
import { DashboardApiService } from './dashboard-api.service';

@Injectable({
  providedIn: 'root',
})
export class AppointmentApiService {
  // private appointments: Appointment[] = [
  //   {
  //     id: 11,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 11:50:20'),
  //     endedAt: new Date('02-01-2023 12:30:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 1,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 11:50:20'),
  //     endedAt: new Date('02-01-2023 12:30:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 3,
  //       firstname: 'David',
  //       lastname: 'Warner',
  //       userType: UserType.General,
  //       email: 'david@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 3,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 2,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 11:50:20'),
  //     endedAt: new Date('02-01-2023 12:30:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 3,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 11:50:20'),
  //     endedAt: new Date('02-01-2023 12:30:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 4,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 11:50:20'),
  //     endedAt: new Date('02-01-2023 12:30:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 5,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 11:50:20'),
  //     endedAt: new Date('02-01-2023 12:30:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 6,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 11:50:20'),
  //     endedAt: new Date('02-01-2023 12:30:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 7,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 2:50:00'),
  //     endedAt: new Date('02-01-2023 3:20:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 8,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 12:45:00'),
  //     endedAt: new Date('02-01-2023 13:15:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 9,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 12:30:00'),
  //     endedAt: new Date('02-01-2023 13:30:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 10,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'David',
  //     patientLname: 'Warner',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date(),
  //     endedAt: new Date(new Date().setHours(new Date().getHours() + 1)),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'David',
  //       lastname: 'Warner',
  //       userType: UserType.General,
  //       email: 'david@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         user: [
  //           {
  //             id: 5,
  //             firstname: 'Jennifer',
  //             lastname: 'Woodley',
  //             userType: UserType.Assistant,
  //             email: 'jennifer@deflexmo.be',
  //             telephone: '9812345678',
  //             address: '',
  //             status: Status.Inactive,
  //             availabilityType: AvailabilityType.Unavailable,
  //             deletedBy: null,
  //             examList: [],
  //             gsm: '',
  //             practiceAvailability: [],
  //           },
  //         ],
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 12,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Jennifer',
  //     patientLname: 'Lawrence',
  //     patientEmail: 'jennifer@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date(new Date().setMonth(new Date().getMonth() + 1)),
  //     endedAt: new Date(
  //       new Date(new Date().setMonth(new Date().getMonth() + 1)).setMinutes(
  //         new Date(new Date().setMonth(new Date().getMonth() + 1)).getMinutes() + 30,
  //       ),
  //     ),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         user: [
  //           {
  //             id: 5,
  //             firstname: 'Jennifer',
  //             lastname: 'Woodley',
  //             userType: UserType.Assistant,
  //             email: 'jennifer@deflexmo.be',
  //             telephone: '9812345678',
  //             address: '',
  //             status: Status.Inactive,
  //             availabilityType: AvailabilityType.Unavailable,
  //             deletedBy: null,
  //             examList: [],
  //             gsm: '',
  //             practiceAvailability: [],
  //           },
  //         ],
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  //   {
  //     id: 13,
  //     doctorId: 1,
  //     doctor: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       email: 'maaike@dfm.com',
  //       address: 'Belgium',
  //       rizivNumber: '89SK98',
  //       telephone: 9878786757,
  //       gsm: 'GSM879',
  //       notifyDoctor: true,
  //       count: 0,
  //       status: Status.Active,
  //     },
  //     patientFname: 'Maaike',
  //     patientLname: 'Benoit',
  //     patientEmail: 'maaike@dfm.com',
  //     patientTel: 7939237883,
  //     examName: '',
  //     roomType: RoomType.Public,
  //     comments: 'Test comment',
  //     approval: AppointmentStatus.Pending,
  //     rejectReason: '',
  //     readStatus: ReadStatus.Unread,
  //     startedAt: new Date('02-01-2023 11:50:20'),
  //     endedAt: new Date('02-01-2023 12:30:00'),
  //     createdBy: 7,
  //     updatedBy: 0,
  //     cancelTillTime: '',
  //     examList: [1, 2],
  //     user: {
  //       id: 1,
  //       firstname: 'Maaike',
  //       lastname: 'Benooit',
  //       userType: UserType.General,
  //       email: 'maaike@deflexmo.be',
  //       telephone: '9812345678',
  //       address: '',
  //       status: Status.Inactive,
  //       availabilityType: AvailabilityType.Unavailable,
  //       deletedBy: null,
  //       gsm: '',
  //       examList: [1, 2, 3, 5, 6, 7, 8],
  //       practiceAvailability: [
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //         {
  //           id: 60,
  //           weekday: Weekday.FRI,
  //           dayStart: new Date(),
  //           dayEnd: new Date(),
  //         },
  //       ],
  //     },
  //     userId: 1,
  //     exams: [
  //       {
  //         id: 1,
  //         name: 'test',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 1,
  //         radiologistCount: 1,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Active,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //         rooms: [
  //           {
  //             id: 1,
  //             name: 'John Room',
  //             description: 'Test Room',
  //             type: RoomType.Public,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Inactive,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [1, 2],
  //           },
  //           {
  //             id: 2,
  //             name: 'Tim Room',
  //             description: 'General Room',
  //             type: RoomType.Private,
  //             availabilityType: AvailabilityType.Available,
  //             status: Status.Active,
  //             placeInAgenda: 0,
  //             roomNo: 1,
  //             practiceAvailability: [],
  //             examLists: [3, 4],
  //           },
  //         ],
  //       },
  //       {
  //         id: 2,
  //         name: 'Exam 1',
  //         expensive: 10,
  //         info: 'test',
  //         assistantCount: 2,
  //         radiologistCount: 2,
  //         nursingCount: 1,
  //         secretaryCount: 1,
  //         availabilityType: AvailabilityType.Available,
  //         status: Status.Inactive,
  //         usersList: [],
  //         roomsForExam: [],
  //         uncombinables: [],
  //         practiceAvailability: [],
  //       },
  //     ],
  //   },
  // ];

  private refreshAppointment$$ = new Subject<void>();

  constructor(
    private physicianApiSvc: PhysicianApiService,
    private staffApiSvc: StaffApiService,
    private http: HttpClient,
    private dashboardApiService: DashboardApiService,
  ) {}

  public get appointment$(): Observable<Appointment[]> {
    return combineLatest([this.refreshAppointment$$.pipe(startWith(''))]).pipe(switchMap(() => this.fetchAllAppointments$()));
  }

  private fetchAllAppointments$(): Observable<Appointment[]> {
    return this.http.get<BaseResponse<Appointment[]>>(`${environment.serverBaseUrl}/appointment`).pipe(map((response) => response.data));
  }

  public changeAppointmentStatus$(changes: { id: number | string; newStatus: AppointmentStatus | null }[]): Observable<boolean> {
    // if (!changes.length) {
    //   return of(false);
    // }
    //
    // let changed = false;
    // changes.forEach((change) => {
    //   const index = this.appointments.findIndex((appointment) => appointment.id === +change.id);
    //   if (index !== -1 && change.newStatus !== null) {
    //     this.appointments[index] = {
    //       ...this.appointments[index],
    //       approval: change.newStatus,
    //     };
    //
    //     if (!changed) {
    //       changed = true;
    //     }
    //   }
    // });

    // this.refreshAppointment$$.next();
    //
    return of(true);
  }

  public deleteAppointment$(appointmentID: number): Observable<boolean> {
    return this.http.delete<BaseResponse<boolean>>(`${environment.serverBaseUrl}/appointment/${appointmentID}`).pipe(
      map((response) => response.data),
      tap(() => {
        this.refreshAppointment$$.next();
        this.dashboardApiService.refreshAppointments();
      }),
    );
  }

  public getAppointmentByID(appointmentID: number): Observable<Appointment | undefined> {
    let queryParams = new HttpParams();
    queryParams = queryParams.append('id', appointmentID);

    return combineLatest([this.refreshAppointment$$.pipe(startWith(''))]).pipe(
      switchMap(() =>
        this.http.get<BaseResponse<Appointment>>(`${environment.serverBaseUrl}/appointment`, { params: queryParams }).pipe(
          map((response) => {
            if (Array.isArray(response.data)) {
              return response.data[0];
            }
            return response.data;
          }),
          catchError((e) => {
            console.log('error', e);
            return of({} as Appointment);
          }),
        ),
      ),
    );
  }

  public saveAppointment$(requestData: AddAppointmentRequestData) {
    const { id, ...restData } = requestData;
    return this.http
      .post<BaseResponse<AddAppointmentRequestData>>(`${environment.serverBaseUrl}/appointment`, restData)
      .pipe(map((response) => response.data));
  }

  public updateAppointment$(requestData: AddAppointmentRequestData) {
    const { id, ...restData } = requestData;
    return this.http.put<BaseResponse<AddAppointmentRequestData>>(`${environment.serverBaseUrl}/appointment/${id}`, restData).pipe(
      map((response) => response.data),
      tap(() => this.refreshAppointment$$.next()),
    );
  }

  public updateReadStatus(appointmentID: number) {
    // const index = this.appointments.findIndex((appointment) => +appointment.id === +appointmentID);
    // if (index !== -1) {
    //   console.log(this.appointments[index]);
    //   this.appointments[index].readStatus = ReadStatus.Read;
    //   this.refreshAppointment$$.next();
    //   console.log(this.appointments[index]);
    // }
  }

  public changeRadiologist(appointmentID: number, radiologistID: number) {
    // const index = this.appointments.findIndex((appointment) => +appointment.id === +appointmentID);
    // if (index !== -1) {
    //   console.log(this.appointments[index]);
    //   this.appointments[index].doctorId = radiologistID;
    //   this.refreshAppointment$$.next();
    // }
  }

  public updateAppointmentDuration(requestData: UpdateDurationRequestData) {
    const { id, ...restData } = requestData;

    return this.http.put<BaseResponse<any>>(`${environment.serverBaseUrl}/updateappointmentduration/${id}`, restData).pipe(
      map((response) => {
        console.log(response);
        return response;
      }),
      tap(() => this.refreshAppointment$$.next()),
    );
  }
}
