import { Injectable } from '@angular/core';
import { catchError, combineLatest, map, Observable, of, startWith, Subject, switchMap } from 'rxjs';
import { AddAppointmentRequestData, Appointment } from '../../shared/models/appointment.model';
import { AppointmentStatus, ReadStatus, Status } from '../../shared/models/status';
import { RoomType } from '../../shared/models/rooms.model';
import { AvailabilityType, User, UserType } from '../../shared/models/user.model';
import { Weekday } from '../../shared/models/calendar.model';
import { PhysicianApiService } from './physician.api.service';
import { StaffApiService } from './staff-api.service';
import { Physician } from '../../shared/models/physician.model';
import { BaseResponse } from 'src/app/shared/models/base-response.model';
import { environment } from 'src/environments/environment';
import { HttpClient, HttpParams } from '@angular/common/http';

@Injectable({
  providedIn: 'root',
})
export class AppointmentApiService {
  private appointments: Appointment[] = [
    {
      id: 11,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 1,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 3,
        firstname: 'David',
        lastname: 'Warner',
        userType: UserType.General,
        email: 'david@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 3,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 2,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 3,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 4,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 5,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 6,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 7,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 8,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 9,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 10,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 12,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
    {
      id: 13,
      doctorId: 1,
      doctor: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        email: 'maaike@dfm.com',
        address: 'Belgium',
        rizivNumber: '89SK98',
        telephone: 9878786757,
        gsm: 'GSM879',
        notifyDoctor: true,
        count: 0,
        status: Status.Active,
      },
      patientFname: 'Maaike',
      patientLname: 'Benoit',
      patientEmail: 'maaike@dfm.com',
      patientTel: 7939237883,
      examName: '',
      roomType: RoomType.Public,
      comments: 'Test comment',
      approval: AppointmentStatus.Pending,
      rejectReason: '',
      readStatus: ReadStatus.Unread,
      startedAt: new Date('02-01-2023 11:50:20'),
      endedAt: new Date('06-01-2023 11:50:00'),
      createdBy: 7,
      updatedBy: 0,
      cancelTillTime: '',
      examList: [1, 2],
      user: {
        id: 1,
        firstname: 'Maaike',
        lastname: 'Benooit',
        userType: UserType.General,
        email: 'maaike@deflexmo.be',
        telephone: '9812345678',
        address: '',
        status: Status.Inactive,
        availabilityType: AvailabilityType.Unavailable,
        deletedBy: null,
        gsm: '',
        examList: [1, 2, 3, 5, 6, 7, 8],
        practiceAvailability: [
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
          {
            id: 60,
            weekday: Weekday.FRI,
            dayStart: new Date(),
            dayEnd: new Date(),
          },
        ],
      },
      userId: 1,
      exams: [
        {
          id: 1,
          name: 'test',
          expensive: 10,
          info: 'test',
          assistantCount: 1,
          radiologistCount: 1,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Active,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
          rooms: [
            {
              id: 1,
              name: 'John Room',
              description: 'Test Room',
              type: RoomType.Public,
              availabilityType: AvailabilityType.Available,
              status: Status.Inactive,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [1, 2],
            },
            {
              id: 2,
              name: 'Tim Room',
              description: 'General Room',
              type: RoomType.Private,
              availabilityType: AvailabilityType.Available,
              status: Status.Active,
              placeInAgenda: 0,
              roomNo: 1,
              practiceAvailability: [],
              examLists: [3, 4],
            },
          ],
        },
        {
          id: 2,
          name: 'Exam 1',
          expensive: 10,
          info: 'test',
          assistantCount: 2,
          radiologistCount: 2,
          nursingCount: 1,
          secretaryCount: 1,
          availabilityType: AvailabilityType.Available,
          status: Status.Inactive,
          usersList: [],
          roomsForExam: [],
          uncombinables: [],
          practiceAvailability: [],
        },
      ],
    },
  ];

  private refreshAppointment = new Subject<void>();

  constructor(private physicianApiSvc: PhysicianApiService, private staffApiSvc: StaffApiService, private http: HttpClient) {}

  public get appointment$(): Observable<Appointment[]> {
    return combineLatest([this.refreshAppointment.pipe(startWith(''))]).pipe(switchMap(() => of(this.appointments)));
  }

  // public upsertAppointment$(requestData: AddAppointmentRequestData): Observable<string> {
  //   // this.appointments = requestData;
  //   if (requestData.id) {
  //     const index = this.appointments.findIndex((appointments) => appointments.id === requestData.id);
  //     if (index !== -1) {
  //       this.appointments[index] = {
  //         ...this.appointments[index],
  //         patientFname: requestData.patientFname ?? this.appointments[index].patientFname,
  //         patientLname: requestData.patientLname ?? this.appointments[index].patientLname,
  //         patientEmail: requestData.patientEmail ?? this.appointments[index].patientEmail,
  //         patientTel: requestData.patientTel ?? this.appointments[index].patientTel,
  //         doctorId: requestData.doctorId ?? this.appointments[index].doctorId,
  //         userId: requestData.userId ?? this.appointments[index].userId,
  //         approval: requestData.approval ?? this.appointments[index].approval,
  //         examList: requestData.examList ?? this.appointments[index].examList,
  //         startedAt: requestData.startedAt ?? this.appointments[index].startedAt,
  //         endedAt: requestData.startedAt
  //           ? new Date(new Date(requestData.startedAt).setDate(new Date(requestData.startedAt).getDate() + 2))
  //           : this.appointments[index].endedAt,
  //         roomType: requestData.roomType ?? this.appointments[index].roomType,
  //         comments: requestData.comments ?? this.appointments[index].comments,
  //       };

  //       if (requestData.doctorId) {
  //         this.physicianApiSvc.getPhysicianByID(+requestData.doctorId).subscribe((doctor) => {
  //           this.appointments[index].doctor = doctor as Physician;
  //         });
  //       }

  //       if (requestData.userId) {
  //         this.staffApiSvc.getStaffByID(+requestData.userId).subscribe((user) => {
  //           this.appointments[index].user = user as User;
  //         });
  //       }
  //     }
  //   } else {
  //     this.appointments.push({
  //       id: Math.floor(Math.random() * 100),
  //       patientFname: requestData.patientFname,
  //       patientLname: requestData.patientLname,
  //       patientEmail: requestData.patientEmail,
  //       patientTel: requestData.patientTel,
  //       doctorId: requestData.doctorId,
  //       doctor: {} as Physician,
  //       userId: requestData.userId,
  //       user: {} as User,
  //       approval: requestData.approval ?? AppointmentStatus.Pending,
  //       examList: requestData.examList,
  //       startedAt: requestData.startedAt,
  //       endedAt: new Date(new Date(requestData.startedAt).setDate(new Date(requestData.startedAt).getDate() + 2)),
  //       roomType: requestData.roomType,
  //       comments: requestData.comments ?? '',
  //       readStatus: ReadStatus.Unread,
  //       rejectReason: '',
  //     });

  //     this.physicianApiSvc.getPhysicianByID(+requestData.doctorId).subscribe((doctor) => {
  //       this.appointments[this.appointments.length - 1].doctor = doctor as Physician;
  //     });

  //     this.staffApiSvc.getStaffByID(+requestData.userId).subscribe((user) => {
  //       this.appointments[this.appointments.length - 1].user = user as User;
  //     });
  //   }

  //   this.refreshAppointment.next();

  //   return of('Saved');
  // }

  public changeAppointmentStatus$(changes: { id: number | string; newStatus: AppointmentStatus | null }[]): Observable<boolean> {
    if (!changes.length) {
      return of(false);
    }

    let changed = false;
    changes.forEach((change) => {
      const index = this.appointments.findIndex((appointment) => appointment.id === +change.id);
      if (index !== -1 && change.newStatus !== null) {
        this.appointments[index] = {
          ...this.appointments[index],
          approval: change.newStatus,
        };

        if (!changed) {
          changed = true;
        }
      }
    });

    this.refreshAppointment.next();

    return of(true);
  }

  public deleteAppointment(appointmentID: number) {
    const index = this.appointments.findIndex((appointment) => appointment.id === +appointmentID);
    if (index !== -1) {
      this.appointments.splice(index, 1);
      this.refreshAppointment.next();
    }

    return this.http
      .delete<BaseResponse<Boolean>>(`${environment.serverBaseUrl}/appointment/${appointmentID}`)
      .pipe(map((response) => response.data));
  }

  public getAppointmentByID(appointmentID: number): Observable<Appointment | undefined> {
    console.log('appointmentID: ', appointmentID);
    let queryParams = new HttpParams();
    queryParams = queryParams.append('id', appointmentID);
    return combineLatest([this.refreshAppointment.pipe(startWith(''))]).pipe(
      switchMap(() =>
        this.http.get<BaseResponse<Appointment>>(`${environment.serverBaseUrl}/appointment`, {params: queryParams})
        .pipe(
          map((response) => response.data), 
          catchError((e) =>{
            console.log("error", e)
            return of({} as Appointment)
        })
        )))
  }

  public saveAppointment$(requestData: AddAppointmentRequestData){
    const {id, ...restData} = requestData;
    return this.http.post<BaseResponse<AddAppointmentRequestData>>(`${environment.serverBaseUrl}/appointment`, restData).pipe(
      map(response => response.data)
    )
  }

  public updateAppointment$(requestData: AddAppointmentRequestData){
    const {id, ...restData} = requestData;
    return this.http.put<BaseResponse<AddAppointmentRequestData>>(`${environment.serverBaseUrl}/appointment/${id}`, restData).pipe(
      map(response => response.data)
    )
  }

}