import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Exam } from '../../shared/models/exam.model';

@Injectable({
  providedIn: 'root',
})
export class ExamApiService {
  private exams: Exam[] = [
    {
      id: 1,
      name: 'test',
      expensive: 10,
      info: 'test',
      assistantCount: 1,
      radiologistCount: 1,
      nursingCount: 1,
      secretaryCount: 1,
      availabilityType: 1,
      status: 1,
      usersList: [],
      roomsForExam: [],
      uncombinables: [],
      practiceAvailability: null,
    },
    {
      id: 2,
      name: 'Exam 1',
      expensive: 10,
      info: 'test',
      assistantCount: 2,
      radiologistCount: 2,
      nursingCount: 1,
      secretaryCount: 1,
      availabilityType: 1,
      status: 1,
      usersList: [],
      roomsForExam: [],
      uncombinables: [],
      practiceAvailability: null,
    },
    {
      id: 3,
      name: 'Exam 2',
      expensive: 10,
      info: 'test',
      assistantCount: 2,
      radiologistCount: 2,
      nursingCount: 1,
      secretaryCount: 1,
      availabilityType: 1,
      status: 1,
      usersList: [],
      roomsForExam: [],
      uncombinables: [],
      practiceAvailability: null,
    },
    {
      id: 4,
      name: 'Exam 3',
      expensive: 10,
      info: 'test',
      assistantCount: 2,
      radiologistCount: 2,
      nursingCount: 1,
      secretaryCount: 1,
      availabilityType: 1,
      status: 0,
      usersList: [],
      roomsForExam: [],
      uncombinables: [],
      practiceAvailability: null,
    },
    {
      id: 5,
      name: 'Exam 4',
      expensive: 10,
      info: 'test',
      assistantCount: 2,
      radiologistCount: 2,
      nursingCount: 1,
      secretaryCount: 1,
      availabilityType: 1,
      status: 1,
      usersList: [],
      roomsForExam: [],
      uncombinables: [],
      practiceAvailability: null,
    },
    {
      id: 6,
      name: 'Exam 5',
      expensive: 10,
      info: 'test',
      assistantCount: 2,
      radiologistCount: 2,
      nursingCount: 1,
      secretaryCount: 1,
      availabilityType: 1,
      status: 1,
      usersList: [],
      roomsForExam: [],
      uncombinables: [],
      practiceAvailability: null,
    },
    {
      id: 7,
      name: 'sugar',
      expensive: 10,
      info: 'test',
      assistantCount: 2,
      radiologistCount: 2,
      nursingCount: 1,
      secretaryCount: 1,
      availabilityType: 0,
      status: 0,
      usersList: [],
      roomsForExam: [],
      uncombinables: [],
      practiceAvailability: null,
    },
    {
      id: 8,
      name: 'esr',
      expensive: 10,
      info: 'test',
      assistantCount: 2,
      radiologistCount: 2,
      nursingCount: 1,
      secretaryCount: 1,
      availabilityType: 1,
      status: 1,
      usersList: [],
      roomsForExam: [],
      uncombinables: [],
      practiceAvailability: null,
    },
  ];

  constructor() {}

  public get exams$(): Observable<Exam[]> {
    return of(this.exams);
  }
}
