name: Diflexmo scheduler admin UI

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: Diflexmo-Scheduler-UI-PRD
    steps:
      - checkout: self
        submodules: true
      - task: replacetokens@5
        displayName: 'Update environment values'
        inputs:
          targetFiles: '**/environment.pipeline.ts'
          encoding: 'auto'
          tokenPattern: 'azpipelines'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          enableRecursion: false
          useLegacyPattern: false
          enableTelemetry: true
      - task: Bash@3
        displayName: 'Copy environment file'
        inputs:
          targetType: 'inline'
          script: 'cp ./src/environments/environment.pipeline.ts ./src/environments/environment.prod.ts'
      - task: Npm@1
        displayName: 'npm install'
        inputs:
          command: 'custom'
          customCommand: 'install --force'
          customRegistry: 'useFeed'
          customFeed: '18e540ed-207f-4a1e-8e3b-014618dd9c9a'
      - script: |
          npm install -g @angular/cli
          npm install
          ng build --configuration production --base-href /admin/
      - task: Bash@3
        displayName: 'Copy staticwebapp.config.json'
        inputs:
          targetType: 'inline'
          script: 'cp ./staticwebapp.config.json ./dist/diflexmo-admin/staticwebapp.config.json'
      - task: AzureStaticWebApp@0
        displayName: 'Deploy static web app'
        inputs:
          skip_app_build: true
          #app_build_command: 'npm install --force && npm run build --configuration=production'
          azure_static_web_apps_api_token: $(admin-deployment-token)
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: './dist/diflexmo-admin' # App source code path
###### End of Repository/Build Configurations ######
